// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlssrbkoxndiprbfjunk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsc3NyYmtveG5kaXByYmZqdW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNzcxNjUsImV4cCI6MjA4ODc1MzE2NX0.2PeP3mUeg1XJIxaCdj4FR8E9REw4TpHHFfSCoO-8XuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});